//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Rendimiento_Frontend.Recursos.Shared {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensajeRecurso {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensajeRecurso() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gestion_Rendimiento_Frontend.Recursos.Shared.MensajeRecurso", typeof(MensajeRecurso).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de anular la información?.
        /// </summary>
        public static string ConfirmacionAnular {
            get {
                return ResourceManager.GetString("ConfirmacionAnular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar la información?.
        /// </summary>
        public static string ConfirmacionEliminar {
            get {
                return ResourceManager.GetString("ConfirmacionEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de registrar la información.
        /// </summary>
        public static string ConfirmacionGuardar {
            get {
                return ResourceManager.GetString("ConfirmacionGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe guardar los datos del.
        /// </summary>
        public static string DebeGuardarDatosGenerales {
            get {
                return ResourceManager.GetString("DebeGuardarDatosGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ejecuto ningun proceso..
        /// </summary>
        public static string EjecutoNingunProceso {
            get {
                return ResourceManager.GetString("EjecutoNingunProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al grabar el registro..
        /// </summary>
        public static string ErroralGrabar {
            get {
                return ResourceManager.GetString("ErroralGrabar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se procesó correctamente..
        /// </summary>
        public static string MensajeProceso {
            get {
                return ResourceManager.GetString("MensajeProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se anuló la informacion con éxito..
        /// </summary>
        public static string SeAnuloRegistro {
            get {
                return ResourceManager.GetString("SeAnuloRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se eliminó la información con éxito..
        /// </summary>
        public static string SeEliminoInformacionExito {
            get {
                return ResourceManager.GetString("SeEliminoInformacionExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se guardó la información con éxito..
        /// </summary>
        public static string SeGuardoInformacionExito {
            get {
                return ResourceManager.GetString("SeGuardoInformacionExito", resourceCulture);
            }
        }
    }
}
